spring:
  datasource:
    url: jdbc:mysql://112.124.4.172:3306/ashop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: your127@Y
  thymeleaf:
    prefix: classpath:/static/
    cache: false
    suffix: .html
  redis:
    database: 0
    host: localhost
    port: 6379
    #password: 默认为空
    #lettuce:
    # pool:
    #    max-active: 8
    # shutdown-timeout: 100ms
SSOConfig:
  url: http://localhost:8098/log