spring:
  datasource:
    url: jdbc:mysql://112.124.4.172:3306/ashop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    data-username: root
    data-password: your127@Y
    driver-class-name: com.mysql.cj.jdbc.Driver